//Base de Datos temporal, falta algo por exportar e importar.
//Se exporto la variable "seeds" pero las URL de imagenes
//viene de otro obejeto imags. QUiero saber como importar los dos
//para que se renderice bien el componente.
const axisEnums = {
  EC: 1,
  IM: 2,
  CA: 3,
  ALL: 4,
};
//Imagenes
const imgs = {
  AlexanderCruz:"No sirve el link",
  sNombre1:                  "https://live.staticflickr.com/65535/50801478796_96d21723cc_k.jpg",
  AnaZapata:                 "https://live.staticflickr.com/65535/50801479281_4fd5f8fd19_h.jpg",
  LorenBustos:               "https://live.staticflickr.com/65535/50801597487_8c52b65b48_k.jpg",
  DanielaMartinez:           "https://live.staticflickr.com/65535/50801479771_4ac38ac934_k.jpg",
  DanielaEscobar:            "https://live.staticflickr.com/65535/50800738768_3cfcdb5e04_b.jpg",
  JuanMartinez:              "https://live.staticflickr.com/65535/50801598387_c78c434bd5_k.jpg",
  AndresWernet:              "https://live.staticflickr.com/65535/50801480621_56642f9799_z.jpg",
  MariLarios:                "https://live.staticflickr.com/65535/50801598887_b2a0087e22_z.jpg",
  CiroPersa:                 "https://live.staticflickr.com/65535/50800739818_baae417d1e.jpg",
  JuanGomez:                 "https://live.staticflickr.com/65535/50800740723_3d5fe9e0aa_k.jpg",
  DanielaBada:               "https://live.staticflickr.com/65535/50801600382_543b93d4d7_k.jpg",
  Sergio:                    "https://live.staticflickr.com/65535/50801601192_d4aa604ed8_k.jpg",
  KnutNicolayWaaleCova:      "https://live.staticflickr.com/65535/50801602047_1eb68f5ce4_h.jpg",
  AdrianaLuciaCardozoPenagos:"https://live.staticflickr.com/65535/50800742383_7f7236463d_m.jpg",
  VictorFernandezAbadia:     "https://live.staticflickr.com/65535/50801484416_73b8cef587_b.jpg",
  ValeriaSanchez:            "https://live.staticflickr.com/65535/50800743648_a832f93f61_k.jpg",
  DanielCruzSilva:           "https://live.staticflickr.com/65535/50801603152_261efcf6e7_c.jpg",
  LauraMorenoLesmes:         "https://live.staticflickr.com/65535/50800744718_1411088755_k.jpg",
  NataliaBernalUrrego:       "https://live.staticflickr.com/65535/50800744893_a0e6b3b8e9_k.jpg",
  SergioDanielLuengas:       "https://live.staticflickr.com/65535/50800745463_299d286515_k.jpg",
  JohnPulido:                "https://live.staticflickr.com/65535/50801487076_6b1b1974f3_k.jpg",
  ArcaneGamesPro:            "https://live.staticflickr.com/65535/50800746223_a9f61ee781_k.jpg",
  PaulaHernandez:            "https://live.staticflickr.com/65535/50800746438_0871aa782f_b.jpg",
  SebastianManrique:         "https://live.staticflickr.com/65535/50801488411_9826ce8d12_k.jpg",
  HeiddyMath:                "https://live.staticflickr.com/65535/50801489031_a28f480b26_n.jpg",
  JulianGarcia:              "https://live.staticflickr.com/65535/50800748608_57565d9844_k.jpg",
  SofiaBeltran:              "https://live.staticflickr.com/65535/50800748643_0cce0701a6_b.jpg",
}
//Paises
const nacionalidades ={
  "CO":"Colomia",
  "FR":"Francia",
  "CH":"Chile",
  "EU":"Estados Unidos",
  "EC":"Ecuador",
  "ES":"Espania",
  "VE":"Venezuela",
  "AR":"Argentina"
}


const model = {
  name: null,
  roleDescription: null,
  background: null,
  axis: null,
  birthDate: null,
  nationality: null,
  locationCity: null,
  locationCountry: null,
  occupation: null,
  email: null,
  admissionDate: null,
  exitDate: null,
};

const seeds = [
  {
    seq: 1,
    name: "Robinson Alexander Devia Gonzalez",
    roleDescription: "Estructuración Cerros del Cambio (Mentores y asesores)",
    background: "Administrador de Empresas",
    axis: 1,
    birthDate: "08/06/1973",
    nationality: "CO",
    locationCity: "Medellín",
    locationCountry: "CO",
    occupation: "Administrador de Empresas",
    email: "radg99@hotmail.com",
    admissionDate: "22/05/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 2,
    name: "Julián Andrés García Valero",
    roleDescription: "Tigrillo: el flow de los cerros",
    background: null,
    axis: 1,
    birthDate: "19/11/1986",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: null,
    email: "juliangarciavalero@hotmail.com",
    admissionDate: "03/06/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 3,
    name: "Alexánder Cruz Ordóñez",
    roleDescription:
      "Tigrillo: el flow de los cerros, Grupo de Apoyo (Psicología y Trabajo Social)",
    background: null,
    axis: 1,
    birthDate: "18/02/1991",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: null,
    email: "psg.alexandercruz@gmail.com",
    admissionDate: "10/03/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 4,
    name: "Natalia Bernal Urrego",
    roleDescription: "Grupo de Apoyo (Psicología y Trabajo Social)",
    background: null,
    axis: 1,
    birthDate: "03/01/1992",
    nationality: "CO",
    locationCity: "Medellín",
    locationCountry: "CO",
    occupation: null,
    email: "nataliabernalu@hotmail.com",
    admissionDate: "01/08/2020",
    exitDate: null,
    imageURL: imgs.NataliaBernalUrrego,
  },
  {
    seq: 5,
    name: "Manuela Ramos Jaramillo",
    roleDescription:
      "Marketing (Redes sociales y web del proyecto), Profesores Voluntarios (clases y talleres)",
    background: "Biología, Química",
    axis: 1,
    birthDate: "18/05/1992",
    nationality: "CO",
    locationCity: "Manizales, Caldas",
    locationCountry: "CO",
    occupation: "Biología, Química",
    email: "animanuela.5@gmail.com",
    admissionDate: "01/06/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 6,
    name: "Daniela Badalacchi Baños",
    roleDescription:
      "Articulación con el fin de lograr la prestación de servicios jurídicos a la comunidad",
    background: "Abogado",
    axis: 1,
    birthDate: "20/05/1993",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Abogado",
    email: "dbadalacchi@gmail.com",
    admissionDate: "28/07/2020",
    exitDate: null,
    imageURL: imgs.DanielaBada,
  },
  {
    seq: 7,
    name: "Andres Wernet",
    roleDescription:
      "Profesores Voluntarios (clases y talleres), Estructuración Cerros del Cambio (Mentores y asesores)",
    background: "Estudiante",
    axis: 1,
    birthDate: "05/12/1993",
    nationality: "UE",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "andres_wernet@hotmail.com",
    admissionDate: "20/01/2020",
    exitDate: null,
    imageURL: imgs.AndresWernet,
  },
  {
    seq: 8,
    name: "Carolína López",
    roleDescription:
      "Marketing (Redes sociales y web del proyecto), Talento humano ",
    background: "Psicólogo",
    axis: 1,
    birthDate: "29/04/1994",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Psicólogo",
    email: "carolina.lr29@gmail.com",
    admissionDate: "25/05/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 10,
    name: "Daniela Korina Mejia Narvaez ",
    roleDescription: "Profesores Voluntarios (clases y talleres)",
    background: "Internacionalista",
    axis: 1,
    birthDate: "14/04/1995",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Internacionalista",
    email: "danielakori@hotmail.com",
    admissionDate: "03/02/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 11,
    name: "Sofía Beltrán",
    roleDescription:
      "YTEL (You Teach Everyone Learns), Estructuración Cerros del Cambio (Mentores y asesores)",
    background: "Internacionalista",
    axis: null,
    birthDate: "22/11/1995",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Internacionalista",
    email: "sofiabeltranb@gmail.com",
    admissionDate: "01/01/2020",
    exitDate: null,
    imageURL: imgs.SofiaBeltran,
  },
  {
    seq: 12,
    name: "Jessica Stefania Quitian Alfonso",
    roleDescription: "Grupo de Apoyo (Psicología y Trabajo Social)",
    background: "Psicólogo",
    axis: 1,
    birthDate: "03/01/1996",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Psicólogo",
    email: "jessi.fania52@gmail.com",
    admissionDate: "01/05/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 13,
    name: "Víctor Julio Fernández Abadía ",
    roleDescription: "Grupo de Apoyo (Psicología y Trabajo Social)",
    background: null,
    axis: 1,
    birthDate: "24/07/1996",
    nationality: "CO",
    locationCity: "La Victoria",
    locationCountry: "CO",
    occupation: null,
    email: "victorfernandezabadia@gmail.com",
    admissionDate: "19/05/2020",
    exitDate: null,
    imageURL: imgs.VictorFernandezAbadia,
  },
  {
    seq: 14,
    name: "Daniela Martinez",
    roleDescription: "Grupo de Apoyo (Psicología y Trabajo Social)",
    background: "Psicólogo",
    axis: null,
    birthDate: "29/08/1996",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Psicólogo",
    email: "dmartinezp.29@gmail.com",
    admissionDate: "13/07/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 15,
    name: "Juan Sebastián Manrique Micolta",
    roleDescription: "YTEL (You Teach Everyone Learns)",
    background:
      "Diseñador, Marketing",
    axis: 2,
    birthDate: "07/09/1996",
    nationality: "CO",
    locationCity: "Medellín",
    locationCountry: "CO",
    occupation: "Diseñador, Marketing",
    email: "sebastianmicolt@gmail.com",
    admissionDate: "05/05/2020",
    exitDate: null,
    imageURL: imgs.SebastianManrique,
  },
  {
    seq: 16,
    name: "Sergio Andrés Suárez Gutiérrez",
    roleDescription: "YTEL (You Teach Everyone Learns)",
    background: "Estudiante",
    axis: 2,
    birthDate: "07/03/1997",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "sergiolin9@gmail.com",
    admissionDate: "01/08/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 17,
    name: "Carolina Alzate Quiroga",
    roleDescription: "Marketing (Redes sociales y web del proyecto)",
    background: "Internacionalista",
    axis: 4,
    birthDate: "11/08/1997",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Internacionalista",
    email: "carolina.alzate@urosario.edu.co",
    admissionDate: "01/07/2019",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 18,
    name: "Angie Acosta",
    roleDescription: "Marketing (Redes sociales y web del proyecto)",
    background: "Periodista",
    axis: axisEnums.ALL,
    birthDate: "16/08/1997",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Periodista",
    email: "p.angiemar97@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 19,
    name: "Galo Alexander Navarrete Bermello",
    roleDescription:
      "Profesores Voluntarios (clases y talleres), YTEL (You Teach Everyone Learns)",
    background: "Ingeniero Eléctrico",
    axis: 2,
    birthDate: "04/10/1997",
    nationality: "EC",
    locationCity: "Portoviejo",
    locationCountry: "EC",
    occupation: "Ingeniero Eléctrico",
    email: "alexgal1004@gmail.com",
    admissionDate: "04/08/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 20,
    name: "Camila Ocasión Martínez ",
    roleDescription: "Profesores Voluntarios (clases y talleres)",
    background: "Investigación",
    axis: 1,
    birthDate: "21/12/1997",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Investigación",
    email: "cami7901@gmail.com",
    admissionDate: "20/02/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 21,
    name: "Paula Hernández",
    roleDescription: "Tutores (Agentes de Cambio)",
    background: "Ingeniero Industrial",
    axis: 1,
    birthDate: "24/01/1998",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Ingeniero Industrial",
    email: "paula.lhviteri@gmail.com",
    admissionDate: "20/05/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 22,
    name: "Karen Daniela Salazar ",
    roleDescription: "YTEL (You Teach Everyone Learns)",
    background: "Fisioterapeuta",
    axis: 1,
    birthDate: "15/02/1998",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Fisioterapeuta",
    email: "danielasalazar15.ds@gmail.com",
    admissionDate: "31/03/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 23,
    name: "Heiddy Paola Salas Luengas",
    roleDescription: "Profesores Voluntarios (clases y talleres), Pre-icfes",
    background: "Matemáticas",
    axis: null,
    birthDate: "21/04/1998",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Matemáticas",
    email: "heiddymath@gmail.com",
    admissionDate: "04/05/2020",
    exitDate: null,
    imageURL: imgs.HeiddyMath,
  },
  {
    seq: 24,
    name: "Loren Alejandra Bustos",
    roleDescription:
      "Profesores Voluntarios (clases y talleres), YTEL (You Teach Everyone Learns)",
    background: "Internacionalista",
    axis: 2,
    birthDate: "05/09/1998",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Internacionalista",
    email: "lorenalejandra14@hotmail.com",
    admissionDate: "21/04/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 25,
    name: "Laura Valentina Moreno Lesmes",
    roleDescription: "Profesores Voluntarios (clases y talleres)",
    background: "Estudiante",
    axis: null,
    birthDate: "25/02/1999",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "laura.moreno.lesmes@gmail.com",
    admissionDate: "28/02/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 26,
    name: "Daniel Cruz",
    roleDescription:
      "Marketing (Redes sociales y web del proyecto), Grupo de Apoyo (Psicología y Trabajo Social), Tutores (Agentes de Cambio), Profesores Voluntarios (clases y talleres), YTEL (You Teach Everyone Learns), Estructuración Cerros del Cambio (Mentores y asesores)",
    background: null,
    axis: null,
    birthDate: "01/10/1999",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: null,
    email: "danieleduardocruzsilva100@hotmail.com",
    admissionDate: "14/02/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 27,
    name: "Angie Sofia Estupiñan Lozano",
    roleDescription: "Tutores (Agentes de Cambio)",
    background: "Economía, Finanzas",
    axis: 1,
    birthDate: "05/11/1999",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Economía, Finanzas",
    email: "angiesofi05@gmail.com",
    admissionDate: "14/07/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 28,
    name: "Juan Pablo Mateus Daza",
    roleDescription: "Donación de Alimentos",
    background: null,
    axis: null,
    birthDate: "23/12/2000",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: null,
    email: "juanpablomateus3@gmail.com",
    admissionDate: "10/04/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 29,
    name: "Stefany Barrero",
    roleDescription: "Tutores (Agentes de Cambio)",
    background: null,
    axis: 1,
    birthDate: "29/11/2001",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: null,
    email: "stefanybarrero@gmail.com",
    admissionDate: "20/07/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 30,
    name: "Ana Maria Zapata ",
    roleDescription: "Tutores (Agentes de Cambio)",
    background: "Internacionalista",
    axis: 1,
    birthDate: "18/01/2002",
    nationality: "CO",
    locationCity: "Montería",
    locationCountry: "CO",
    occupation: "Internacionalista",
    email: "anazapatacano@gmail.com",
    admissionDate: "15/07/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 31,
    name: "Daniela Escobar Rojas",
    roleDescription: "Apadrinamiento",
    background: "Estudiante",
    axis: 1,
    birthDate: "08/03/2002",
    nationality: "ES",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "daniela.escobar@urosario.edu.co",
    admissionDate: "01/06/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 32,
    name: "Grecia Nashira Cuadros Alvarado",
    roleDescription: "Tutores (Agentes de Cambio)",
    background: "Estudiante",
    axis: 1,
    birthDate: "09/03/2002",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "nashcdrs16@gmail.com",
    admissionDate: "01/05/2020",
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 33,
    name: "Sergio Daniel Luengas Santamaría",
    roleDescription:
      "Eje de consciencia ambiental (plástico, huerta urbana y siembra de árboles)",
    background: "Vendedor",
    axis: 3,
    birthDate: "21/04/1998",
    nationality: "CO",
    locationCity: "Tunja",
    locationCountry: "CO",
    occupation: "Vendedor",
    email: "sergiodaniel_l@hotmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 34,
    name: "Manuela",
    roleDescription: "Profesores Voluntarios (clases y talleres)",
    background: "Estudiante",
    axis: 2,
    birthDate: "09/08/1995",
    nationality: "FR",
    locationCity: "Tunja",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "manuelazb@hotmail.fr",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 35,
    name: "Adriana Lucia Cardozo Penagos",
    roleDescription:
      "Eje de consciencia ambiental (plástico, huerta urbana y siembra de árboles)",
    background: "Internacionalista",
    axis: 3,
    birthDate: "18/11/1998",
    nationality: "CO",
    locationCity: "Tunja",
    locationCountry: "CO",
    occupation: "Internacionalista",
    email: "adriana.caardozo@urosario.edu.co",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 36,
    name: "Valeria Sánchez Zorro",
    roleDescription:
      "Tutores (Agentes de Cambio), YTEL (You Teach Everyone Learns)",
    background: "Estudiante",
    axis: 1,
    birthDate: "29/10/1999",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "valeriazorro29@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 37,
    name: "John Harvey Pulido Millan",
    roleDescription: "Profesores Voluntarios (clases y talleres)",
    background: "Docente",
    axis: 1,
    birthDate: "04/06/1977",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Docente",
    email: "johnpulidomillan@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
  //*******Duplicado******seq 41 y 38
    seq: 38,
    name: "Juan Martinez",
    roleDescription:
      "Tigrillo: el flow de los cerros, Grupo de Apoyo (Psicología y Trabajo Social), Tutores (Agentes de Cambio)",
    background: "Enfermero, Psicólogo",
    axis: null,
    birthDate: "16/12/1995",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Enfermero, Psicólogo",
    email: "psmartinez.juan@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 39,
    name: "Clément Aurel",
    roleDescription: "Profesores Voluntarios (clases y talleres)",
    background: "Estudiante",
    axis: 2,
    birthDate: "17/10/1997",
    nationality: "FR",
    locationCity: "Fayence",
    locationCountry: "FR",
    occupation: "Estudiante",
    email: "clement.aurel.bba@edhec.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 40,
    name: "Juan Sebastián Gómez López ",
    roleDescription: "Tutores (Agentes de Cambio)",
    background: "Estudiante",
    axis: 1,
    birthDate: "21/09/2000",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "juansebastian2109@hotmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    //*******Duplicado******seq 41 y 38
    seq: 41, 
    name: "Juan Martinez",
    roleDescription:
      "Tigrillo: el flow de los cerros, Grupo de Apoyo (Psicología y Trabajo Social), Tutores (Agentes de Cambio), No sé si estoy en más 😅",
    background: "Enfermero, Psicólogo",
    axis: null,
    birthDate: "16/12/1995",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Enfermero, Psicólogo",
    email: "psmartinez.juan@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 42,
    name: "Mariana Guerrero",
    roleDescription: "Grupo de Apoyo (Psicología y Trabajo Social)",
    background: "Fonoaudiologo",
    axis: 1,
    birthDate: "15/05/1997",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Fonoaudiologo",
    email: "mar0515gt@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 43,
    name: "María José Herrera",
    roleDescription: "Marketing (Redes sociales y web del proyecto)",
    background: null,
    axis: null,
    birthDate: "02/03/1996",
    nationality: "CH",
    locationCity: "Santiago",
    locationCountry: "CH",
    occupation: "Marketing (Redes sociales y web del proyecto)",
    email: "coteherrerasm@hotmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 44,
    name: "Knut Nicolay Waale",
    roleDescription: "Desarrollador Web",
    background: null,
    axis: null,
    birthDate: "16/01/1984",
    nationality: "VE",
    locationCity: "Buenos Aires, Zarate",
    locationCountry: "AR",
    occupation: "Desarrollador Web",
    email: "knutwaale@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
  {
    seq: 45,
    name: "Camilo Andres Luna",
    roleDescription:
      "Marketing (Redes sociales y web del proyecto), Grupo de Apoyo (Psicología y Trabajo Social), Tutores (Agentes de Cambio), Profesores Voluntarios (clases y talleres), YTEL (You Teach Everyone Learns), Estructuración Cerros del Cambio (Mentores y asesores), Eje de consciencia ambiental (plástico, huerta urbana y siembra de árboles)",
    background: "Estudiante",
    axis: null,
    birthDate: "19/07/2000",
    nationality: "CO",
    locationCity: "Bogotá",
    locationCountry: "CO",
    occupation: "Estudiante",
    email: "ultrapicachu30@gmail.com",
    admissionDate: null,
    exitDate: null,
    imageURL: null,
  },
];
export default seeds;
